project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "PhD course: An Introduction to Functional Data Analysis"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule

    right: 
      - icon: github
        href: https://github.com
        
format:
  html:
    theme: flatly
    # theme: styles.scss
    toc: true
