---
title: "Take-Home Exam Description"
subtitle: "Description of the exam datasets, requirements, and timeline"
format: 
  html:
    toc: true
    toc-depth: 2
---

## Exam description and timeline
* the students will receive one or more datasets on Day 3
* they will be requested to analyse one set of data (at their choice) via at least one selected FDA technique among those introduced during the course
* evaluation will be done on a written report (max 2 pages excluding figures and tables) describing the analysis, where the students will be requested to:
    + motivate the choice of analysis
    + describe the chosen methodology
    + visualize and discuss the data and results
* R scripts for carrying out the analysis shall be attached separately
* **deadline for submitting the exam report: April 15^th^, 2024**

## Exam Datasets

**Dataset 1: Sugar Data**

In chemometrics, absorbance or emission spectra from food samples are used to determine the content of certain ingredients. Using the spectra is typically much cheaper than alternative chemical analysis. 

268 samples of sugar were dissolved and the solution was measured
spectrofluorometrically. For every sample the emission spectra from 275–560 nm were measured in 0.5 nm intervals (i.e., at 571 wavelengths) at seven excitation wavelengths: 230, 240, 255, 290, 305, 325, and 340 nm.

In addition, a laboratory measure of the quality of the sugar is also given: ash content (in percentage). Ash content measures the amount of inorganic impurities in the refined sugar.

Data can be downloaded [here](https://github.com/valeriavitelli/PhDcourse_FDA/blob/main/data/Data_Sugar.RDA) ('RDA' files can be loaded in R by simply using the function 'load').

See [this paper](https://www4.stat.ncsu.edu/~staicu/papers/msFGRPL_R1.pdf), Section 5.2, for more information and one example of analysis.


**Dataset 2: AneuRisk65 Data**

The AneuRisk project is a a scientific endeavour that aimed at investigating the role of vessel morphology, blood fluid dynamics and biomechanical properties of the vascular wall, on the pathogenesis of cerebral aneurysms. This has lead to the collection of the benchmark dataset AneuRisk65.

The dataset AneuRisk65 includes image reconstructions of the Inner Carotid Artery (ICA), described in terms of the vessel centreline (in the 3D space) and of the vessel radius and curvature profiles.

The file 'Patients.txt' contains additional information on the 65 patients.

For each patient i, i=1, ..65, the file 'Rawdata-FKS-i.txt' contains
both raw and smoothed ICA data (abscissa, radius, 3 spatial coordinates of the ICA centerline, corresponding first and second derivatives, curvature). 

Data can be downloaded [here](https://github.com/valeriavitelli/PhDcourse_FDA/blob/main/data/AneuRisk65.zip).

See the [README file](https://github.com/valeriavitelli/PhDcourse_FDA/blob/main/data/AneuRisk65_ReadMe.pdf) for more information.
